# Generated by Django 4.1.1 on 2022-09-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_no', models.AutoField(primary_key=True, serialize=False)),
                ('show_name', models.CharField(max_length=50, unique=True)),
                ('speaker', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('venue', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('avl_tkt', models.IntegerField()),
                ('sold_tkt', models.IntegerField()),
            ],
        ),
    ]
