# Generated by Django 4.1.1 on 2022-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('txn_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('showname', models.CharField(max_length=50)),
                ('txntime', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='desc',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='show',
            name='sold_tkt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='show',
            name='venue',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
