# Generated by Django 4.1.1 on 2022-09-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_transaction_alter_show_desc_alter_show_sold_tkt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_id_pu',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
